# Generated by Django 5.1.5 on 2025-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('building', 'Building'), ('road', 'Road'), ('bridge', 'Bridge'), ('dam', 'Dam'), ('tunnel', 'Tunnel')], max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('budget', models.FloatField()),
                ('materials', models.TextField()),
                ('issues', models.TextField(blank=True)),
            ],
        ),
    ]
