# Generated by Django 5.1.5 on 2025-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='issues',
            field=models.CharField(blank=True, choices=[('leakage', 'Leakage'), ('structural damage', 'Structural Damage'), ('corrosion', 'Corrosion'), ('poor water flow', 'Poor Water Flow'), ('cracks', 'Cracks'), ('erosion', 'Erosion')], max_length=50),
        ),
    ]
