# Generated by Django 5.1.5 on 2025-02-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_infrastructure_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(help_text='E.g., monthly, yearly', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('concrete', 'Concrete'), ('steel', 'Steel'), ('wood', 'Wood'), ('glass', 'Glass')], max_length=100)),
                ('suitable_for', models.TextField(help_text='Type of projects this material is suitable for (e.g., bridges, buildings)')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('building', 'Building'), ('bridge', 'Bridge')], max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
        migrations.AddField(
            model_name='maintenanceoption',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.project'),
        ),
    ]
